# Node configuration
node_id: "LINEAR_CORN_A"  # Change this for each node

# Node-specific configurations
node_configs:
  LINEAR_CORN_A:
    lora:
      dev_addr: "260CA983"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  LINEAR_CORN_B:
    lora:
      dev_addr: "260CA984"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  LINEAR_CORN_C:
    lora:
      dev_addr: "260CA985"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  LINEAR_SOY_A:
    lora:
      dev_addr: "260CA986"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  LINEAR_SOY_B:
    lora:
      dev_addr: "260CA987"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  LINEAR_SOY_C:
    lora:
      dev_addr: "260CA988"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  SDI1_CORN_A:
    lora:
      dev_addr: "260CA989"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  SDI1_CORN_B:
    lora:
      dev_addr: "260CA98A"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  SDI1_SOY_A:
    lora:
      dev_addr: "260CA98B"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"
  SDI1_SOY_B:
    lora:
      dev_addr: "260CA98C"
      apps_key: "524F13A6AB0FAF4F92FFEA257DF53423"
      nwks_key: "E31284DAC1D3AED6A72CCDA217046B35"

# Common configurations
datalogger:
  port: "/dev/ttyUSB0"
  baud_rate: 38400

database:
  name: "data/{node_id}.db"

lora:
  region: "US915"
  data_rate: 3

schedule:
  interval_minutes: 30
  transmission_window: 300  # 5 minutes
  min_interval: 10  # 10 seconds minimum between transmissions

sensor_metadata: "config/sensor_mapping.yaml"

# Option to clip float values
clip_floats: true  # Set to true to clip float values to 2 decimal places
