# Node configuration
node_id: "A"  # Change this for each node (A, B, or C)

# Node-specific configurations
node_configs:
  A:
    lora:
      dev_addr: "DEV_ADDR_A"
      apps_key: "APPS_KEY_A"
      nwks_key: "NWKS_KEY_A"
  B:
    lora:
      dev_addr: "DEV_ADDR_B"
      apps_key: "APPS_KEY_B"
      nwks_key: "NWKS_KEY_B"
  C:
    lora:
      dev_addr: "DEV_ADDR_C"
      apps_key: "APPS_KEY_C"
      nwks_key: "NWKS_KEY_C"

# Common configurations
datalogger:
  port: "/dev/ttyUSB0"
  baud_rate: 38400

database:
  name: "data/span2node{node_id}.db"

lora:
  region: "US915"
  data_rate: 3

schedule:
  interval_minutes: 30
  max_random_delay_seconds: 600  # 10 minutes

sensor_metadata: "config/sensor_mapping.yaml"